apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/David-VTUK/turing-pi-ansible.git'
    targetRevision: 'HEAD'
    path: '/argocd-apps/cert-manager'
    helm:
      chart: 'cert-manager-v1.15.3'
      version: 'v1.15.3'
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'cert-manager'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true