apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 'HEAD'
    path: 'argocd-apps/argocd'
    helm:
      chart: 'argo/argocd'
      version: 'v1.15.3'
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'cert-manager'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true