apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: go-auto-instrumentation
spec:
  exporter:
    endpoint: simplest-collector.opentelemetry-operator.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
