apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-autosync
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: hello
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: HEAD
        path: guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

