apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: go-auto-instrumentation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
  namespace: cert-manager
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: go-auto-instrumentation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: go-auto-instrumentation
