apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  template:
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 1.1.1.1