- name: Check If k3s-agent-uninstall.sh exists
  ansible.builtin.stat:
    path: /usr/local/bin/k3s-agent-uninstall.sh
  register: k3s_agent_uninstall_script

- name: Check If k3s-uninstall.sh exists
  ansible.builtin.stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: k3s_uninstall_script

- name: Uninstall K3s agent
  ansible.builtin.shell: |
    /bin/bash -c 'set -o pipefail; /usr/local/bin/k3s-agent-uninstall.sh'
  when: "'agent_nodes' in group_names and k3s_agent_uninstall_script.stat.exists"
  changed_when: false

- name: Uninstall K3s server
  ansible.builtin.shell: |
    /bin/bash -c 'set -o pipefail; /usr/local/bin/k3s-uninstall.sh'
  when: "'server_nodes' in group_names and k3s_uninstall_script.stat.exists"
  changed_when: false

# Nodes need to be rebooted to remove file locks in /mnt/data
- name: Reboot all nodes
  ansible.builtin.reboot:
  when: "'server_nodes' in group_names or 'agent_nodes' in group_names"
  become: true
  failed_when: false

# Remove after reboot
- name: Delete all files in /mnt/data
  ansible.builtin.file:
    path: /mnt/data
    state: absent
  become: true
  failed_when: false
