- name: Apply ArgoCD Applicationset
  kubernetes.core.k8s:
    state: present
    definition:
      - "{{ lookup('file', '../argocd-apps/application-set/applicationset-helm-charts.yaml') }}"
      - "{{ lookup('file', '../argocd-apps/application-set/applicationset-manifests.yaml') }}"

- name: Commit changes to Git
  ansible.builtin.shell: |
      git add ../argocd-apps/*
      git commit -m "Update ArgoCD applications"
      git push
