all:
  vars:
    ansible_python_interpreter: auto_silent

control_plane:
  hosts:
    node-1:
      ansible_host: 172.25.50.241
      tpi_node_number: 1   

workers:
  hosts:
    node-2:
      ansible_host: 172.25.50.242
      tpi_node_number: 2
    node-3:
      ansible_host: 172.25.50.243
      tpi_node_number: 3
    node-4:
      ansible_host: 172.25.50.244
      tpi_node_number: 4