all:
  vars:
    ansible_python_interpreter: auto_silent

control_plane:
  hosts:
    node-1:
      ansible_host: 172.16.10.31
      tpi_node_number: 1   

workers:
  hosts:
    node-2:
      ansible_host: 172.16.10.32
      tpi_node_number: 2
    node-3:
      ansible_host: 172.16.10.33
      tpi_node_number: 3
    node-4:
      ansible_host: 172.16.10.34
      tpi_node_number: 4