# /inventory/hosts

[all]
srv-rk1-01 ansible_host=172.16.10.31
srv-rk1-02 ansible_host=172.16.10.32
srv-rk1-03 ansible_host=172.16.10.33
srv-rk1-04 ansible_host=172.16.10.34

[control_plane_nodes]
srv-rk1-01

[worker_nodes]
srv-rk1-02
srv-rk1-03
srv-rk1-04