cilium:
  # -- Grafana dashboards for cilium-agent
  dashboards:
    enabled: true
    label: grafana_dashboard
    namespace: kube-prometheus-stack
    labelValue: "1"
  bgpControlPlane:
    enabled: true
  envoy:
    prometheus:
      serviceMonitor:
        enabled: true
  gatewayAPI:
    enabled: true
  hubble:
    relay:
      enabled: true
      prometheus:
        serviceMonitor:
          enabled: true
    metrics:
      dashboards:
        enabled: true
        label: grafana_dashboard
        namespace: kube-prometheus-stack
        labelValue: "1"
      enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http
      serviceMonitor:
        enabled: true
    ui:
      enabled: true
  ipam:
    multiPoolPreAllocation: null # https://github.com/cilium/cilium/issues/35811#issuecomment-2645399027
    operator:
      clusterPoolCIDR: 10.42.0.0/16
  operator:
    dashboards:
      enabled: true
      label: grafana_dashboard
      namespace: kube-prometheus-stack
      labelValue: "1"
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  k8sServiceHost: 172.16.10.214
  k8sServicePort: 6443
  kubeProxyReplacement: true
  namespaceOverride: cilium
