cilium:
  bgpControlPlane:
    enabled: true
  envoy:
    prometheus:
      serviceMonitor:
        enabled: true
  gatewayAPI:
    enabled: true
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
  ipam:
    multiPoolPreAllocation: null # https://github.com/cilium/cilium/issues/35811#issuecomment-2645399027
    operator:
      clusterPoolCIDR: 10.42.0.0/16
  k8sServiceHost: 172.16.10.214
  k8sServicePort: 6443
  kubeProxyReplacement: true
  namespaceOverride: cilium
