cilium:
  agent:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  envoy:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  operator:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  bgpControlPlane:
    enabled: true
  gatewayAPI:
    enabled: true
  hubble:
    relay:
      enabled: true
      metrics:
        serviceMonitor:
          enabled: true
    ui:
      enabled: true
  ipam:
    operator:
      clusterPoolCIDR: 10.42.0.0/16
  k8sServiceHost: 172.16.10.221
  k8sServicePort: 6443
  kubeProxyReplacement: true
  namespaceOverride: cilium
