cilium:
  bgpControlPlane:
    enabled: true
  envoy:
    prometheus:
      serviceMonitor:
        enabled: true
  gatewayAPI:
    enabled: true
  hubble:
    relay:
      enabled: true
      prometheus:
        serviceMonitor:
          enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    ui:
      enabled: true
  ipam:
    operator:
      clusterPoolCIDR: 10.42.0.0/16
  operator: 
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  k8sServiceHost: 172.16.10.221
  k8sServicePort: 6443
  kubeProxyReplacement: true
  namespaceOverride: cilium
