grafana:
  global:
    persistence:
      enabled: true
      size: 10Gi
      type: pvc
      volumeName: ""
      accessModes:
        - ReadWriteOnce
    route:
      main:
        enabled: true
        apiVersion: gateway.networking.k8s.io/v1beta1
        kind: HTTPRoute
        hostnames:
         - grafana.virtualthoughts.co.uk
        parentRefs:
          - name: cilium-api-gateway
            namespace: cilium
            sectionName: https-gateway
        matches:
          - path:
              type: PathPrefix
              value: /