apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.cilium.io/'
    chart: 'cilium'
    targetRevision: '1.16.3'
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'cilium'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true