- name: Apply gateway API CRDs
  kubernetes.core.k8s:
    state: present
    src: https://github.com/kubernetes-sigs/gateway-api/releases/download/{{ gateway_api_crd_version }}/experimental-install.yaml

- name: Write gateway API CRD to file
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/gateway-api/releases/download/{{ gateway_api_crd_version }}/experimental-install.yaml
    dest: ../argocd-apps/manifests/gateway-api-crds/experimental-install.yaml
    mode: '0644'
