longhorn:
  namespaceOverride: longhorn
  defaultSettings:
    v2DataEngine: true
    v1DataEngine: false
  preUpgradeChecker:
    jobEnabled: false
  persistence:
    defaultClassReplicaCount: 3
    dataEngine: v2
    defaultDataLocality: best-effort
  defaultSettings:
    defaultDataPath: /dev/nvme0n1
