longhorn:
  namespaceOverride: longhorn
  defaultSettings:
    defaultDataPath: /mnt/data/longhorn/
  preUpgradeChecker:
    jobEnabled: false
  persistence:
    defaultClassReplicaCount: 3
    defaultDataLocality: best-effort