apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: homepage-secrets
  namespace: homepage
spec:
  encryptedData:
    GRAFANA_PASSWORD: AgCgtQ21jRXdAVVYcFMktUZffp1QhKTsnxcwql6zLwPyIFPjwI2mXkTlOrZ9F/53j0w7XCad+dqcGO9sj4rmkVbbbx8GsTws2Zy/sNkqnSJN5TufX5XLaBylE5HSCCEzFFbvp/ubX/ncbz0yDAEp6vxWai5BnstDwjZxvUs4BnWAUGDnWZaezJQxItoOymWpfxrIzaLRMLP/xKVEeHBtcG6eC0M24N7S1YYes/OtuhTpN8mhW58T6gCrw/Rf2u14QrJmz1g6ME35t2nLWdmVuU+MINTtXX4D7tR0BCO0LJ+H1YMRYYAwICWC2YB/W4j6YjDMPY4UYEPzOYYB8uhGLAA1WQpDeWg25rk8EURl4ee+yW0H8zzrnSTV894lKo8nlF8go6xrqvJ6eqFZC3Hys/zDmZols4kjyCPXe5XqzLyBgj0sieyHxjlDH6n8bB365GL/q+BmmAj13HzvFGaw2dfHd4yJfANFIxtDJyduOf9zwFWu7KjwZgRdLVVNig72g6a/dbNnA65cSB3ebpLpTTSMeXhGBO0CUN1FCvZDvLU3ecn+IA/qecSmbU+4F1zAlIWbXXRimjD0Xng+Uea7bx2ABwEarSypm2IpRr6Ct/zJwxMVz5SvqeubLd2zucS7NP/QeAPr6eYTzLUZ9dPmf6AvQt8fZju9jxg5Dzih+AHBdnjATa02mJOCWi6NunkMQt7V7ox7vEhpML3Znh7TRwRK5FvH/ivAQ4ItCQIwS5/onQ==
    GRAFANA_USERNAME: AgCPQDPL98hJREBRCkYVvCtgRaKmMZMlPDM/YK4gZlPaPbBEZr1GJmHyFgmZHH4WflyI6cTWKPsGvwhR5CQFxEBNDGmXQKp8/HJFhE+hT0G/adUNELBxHqaT78JwYlSkar9FGyrRmK4omX/PFgRhodDQn1y0UfXI/30HQYmpOLYC/2A2naCz5lANOV5FWbhxHZFQoNnx926UPUBew7bzNuTMuan45nI+2xQrKVP0Awq+4nXWZtTjxMtBW67ynKxtOXVjX4kW9TCRhRDfso2KUo1DiZ3Opdoi/oHXUSm+FVGir0cT0nkYFbfoab6R9yxukYgS7Pznotr67gpk/InRNC37KTWHcsr97oD115oDWDtGJ93tvFjE56Iu1T1lZoyIKu9wd+vqkkLZ6hcd7N4lIPjXnATp0YCgsUHUDv58Pm06TNbJHC/Oa4joet7xmIcmaQUEAbXALce4bhsILzK0stC19KNC78vi3CdDj2NWL/+kTDrgy2VtZk0gC/6A95C3tz/ubM84N/gMBWYKBjNM2c778PK3pyuHu7jFgoaIemmmSenADCu9/Sq9D7EBUUunSStwMO33q2XS9RCXprLkJFlukmxp5wlXu57urkQyk2xfEBbeKCwaMMhTgB0CM3cGu9djZjdZjmxbGUyDx0urTAvZ83Gm8puM/etVyZv+Jq3fXom/iMMA1sU0dAOQPTZUk7SaxCOEow==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: homepage-secrets
      namespace: homepage
