apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: homepage-secrets
  namespace: homepage
spec:
  encryptedData:
    GRAFANA_PASSWORD: AgCVFyVpPnxqsLgCihcQnwCrYofeis8eiDMdYplm/G6SyuL+3+Cd8pjjACWo0piC+bCCCHrmXub43s6SdjU5rYND+dmo1OS40V0aGMmH3aFlvrgdzY5elIUFDN39ZdZPEIAVm/z6nJth8Cg9tHvi1EOb03r36SMZyUsTrGlGxApB96i7gAPpi0WVhaVxa+tsM1QFBUngBUdM3j21frxBkoUQqAPPHZ8VYE+6AE6c4xgPXTavz383mJsMbe44c1kOiFwg+YwfBpdUlUdbK7FlNod8BXxFJ8v/Nw4m/WojQvtfEkODxAbiZXqjQ3R+ou3RF/b52io4bRGO62FN2nTonKIyFjmb5g47wUGJ0ARdAoRPk1m5mageLqwQU8VuDfoQIuVB8k2Iz6m7x3TU4Eizrm4OmdLi5pdMlnUBtRTdrGjC4VS8HzcOo50GrttOeiyN8B3ki2JRHBKBFXYrCcFeq7KkNWNJ33huLT/vug0dpiFkPb9/0KfpOqsmHONqSoX/n/67kY8QQIYixNJIi63bWeAf2D4zjeab1taxVEguzG1G1y2dVTYBR1V+JOziR0V3/Y8v6Xs6FQ4cAwk2K2pvyr+y+fg+u8hPlly+x7rikRlc+pVH7w2Xqe6ColhOJVvf5vueh6JQ3plD+6lXb2dxkZARkGLbyieiEhR09HnLryt+QyX2sBQdgDUqSM2Rb5IBmgZOcsXeejgTk96VBz3l8lDa
    GRAFANA_USERNAME: AgCVmLfGVxVLmcQf6sBrrx9d4SNjUL3jfZMVfzIRmB4LTS9e6lNPxyV/i7/UWFzdQg6x2j7N4JYa5gy0hjxbKP4CYXNL7VnXjI9MhirZ9w+tL80SybTpnX1yZHb9r6HA9YEteOkFbKDVEDBV2egEJSX0W9YxvVPwnQFXLX5SBd3xyNe9xzbXSGJoV8inHwZ6JkR7Bj9qK324BNqGSYRLyBnlxIAlABIpV1HG90/z2PL2CZTU8nkm4A4/eQm3Op/j/3pmKR/CZ1+BNOTOsV0uFvJNjlOZfnDik3PuOosQGWRiiP5sirvsYvXbn2hmNq0TNhrUMoSOIvOMi7WI+wajHNKoss+rJ6okf8En3zNMmXM/Y5u5W/LDHK6DqaLv6cNC+LGAmLpFSVhMOTLGjaSHCl3ZYH9kav4xjAN3n15z7IkUl2tNw0Q8oztHFm6Hf6FzoKc63auWZlSt1v73+iiKa3qFG+hhKsu6GVDj0Vn1kEw04IsM5Kw1Z6xblsxbOpVPuKGZ3d2MmAhcTBkTFcFOam2bwSiUvXtCkUCUByjOKIU4TQ+bOqKKl4gTQOHKO+//UuBbA1h5OEGdDnWNCW4JGEJ+sq7x1jOgE1e76sOECPo+XIc9J0/IYo1+ukzIyBeiMMCABopOpXx7g/PDLYlMrAT+49uv0WRxC4P39bNTTxDfxDNLRW9a3anK1YcnKcArLniTvdsmzA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: homepage-secrets
      namespace: homepage
