apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: homepage-secrets
  namespace: homepage
spec:
  encryptedData:
    GRAFANA_PASSWORD: AgAjjHtCAw0oTx4DymftOW1VAzSfpT88b9ngov9Gonr4KilFm6DKfNlGjOIQIC9l4JnaYe1jiQuKoTKctYxAl3zOqdFnT/FWK0FpMsieNFODK90cKA6KHn/GkAPHOWABAkG4yfB6MhVhxhfQzUyebmwbbxOGZCw1yBjB8pzLV1yG45s02Wx2LJV2h1o2Qq0b2yjDJAl5GosmvQw30cUecuO+my3lne9XKYE7NVV7zvtap7I3+8HEp1a+CJ++d4qUpFOtzkj2YhUS9fzuW4xIy2FIbWXQvo7t79Nlb7NnpV0WCzFrsNFds42CMJqbyDOCoW1eHWvjBssOvroym8++z7vI3Hm6VV/VaxlG8fjQv9yCH6Bf/0eOH2k9mvZYyMoMp8CWA15w5hNcNXKmQkWGbS1ozTUe/aGF54yD/YedUKKNgqERs6xcz22wOu02b1mCL4cH/W894X9lzN7XMJDZXmyb+smPTFY/XWYXXEIPUxuksd3KfbBn5niIIfuu7hgD8nrS6gPlryt6z9cWKBtcG6kzBCFldxFlxEZmWtRp3J8lI1mt8WhAEeBgddxsJxkX9VuMkitYL+CvKIwcPRVc4ZY6hw5//zxuCETiCmsKcid6WYqqAMuzoDEzie/reOCCzdjhf0LxWV3nBQArpJHn0BA1CVx3zPkkyeB7NqLA4Jod2+gq3P20+YaMRTq6NjsRRF5GNpTuKNYZsAduu65FXePvE2R/5uhc3Bz4QgAc8r9rZw==
    GRAFANA_USERNAME: AgAlGgWNARtkvoaTiSDU51hUs5AVN02LB8M0WFWVnw19bxNoku1Hoc4CgYDRulXvUKqwsVyVn9vrek9dw3V1pCdMeXJOJIIuhCujECLpkGNHnePemkDFhBBHqYpHORYPWjtXFKq0gSIos6zdnqp+Dv8MNgC/RE1VJ6xX6KZp4u1+1eMbEkN6jXUaFw0ypVE4AEU9EdhFfaXzQthXCaYMFr1CduJiE2o9Yr9zsJ4GK4KWsXcb2Xf0u2mn0MbGj1ZGanj6lXdqL11MBJL6ofCwVSIFDPSvMTuEAM5CIpIFx1bkQ84EIgUC7rX7kLQakH+JcnhY+ptrQx6ojgWDvHYf6gP/dsKDZYEO5hsNAQgwcJEtVuO2W8JZdFRMYwqOr/PrVHpJQcD873sp/JljIBtS+EVzQpKBv2DZdmImYs7gKzLbaLLNxPMj7oTDEct2353xYDHyksU0cwWdgiKZuBCLpOBxU8WsTENAy8q5QG6kPtNzV9++q/xm1s2ZdyXGuMgmWLlmc3PcdwLNGHYzre20O1QaA5PoAU3GgeukXzezOMjZXPTtnjHr5BOAUCeRFrsCemCsaOtrBNFzoQwNHK3Yw7Vy2eOw72ec7Bta0c6xVgwGm3Sj9hQ/1ar3FW6jUSgAixrQbhetY7uj5Z7tCafNGbdYoacyyDRlPLWDOzFUgNdTiRlxce1AQ8hkNpfkkD6pqKiPYpK6/Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: homepage-secrets
      namespace: homepage
