apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: adminsecret
  namespace: planka
spec:
  encryptedData:
    password: AgBPCVr9cc/wWsdTd57uBYoxqE/eLem6lH+fVtIkHM2TqvsJ/0IAnyx5ZvoNYQv+DFfzkeo22TRdxEOe9t1PM3l0u/rn8kqsW7BC1CphNNrnsDph3Ro5D98R/PPiCHco1GU8dOzZH5M8eXtz12Lve5Jx87MfD9FObpP2xJxb2ify/qxN+7hLlMhyO3ghbDGEyHTdgW5yCrr77JF+kD2kNht97wh3fqjCCb/+AlEZ+c9AoHwhDv56uawkbqp6L3LzUDuaJKhZt0hSf/ar1vK4OEOBYtZgnME5SwRALn/Am+ndU0ZVOuHWYWNEPj5vtMcZ1J/KnYFQg7e9kuRrV6E1i2VM+bW41TBHMLiYEVd4LmhQxu92rBhbv08739WyNoOBX4hUruDJSnxtGPA8Ee+RtBtEJraU+vyTUoxjwalYyf0F4t+rusWlBe3YN/moKLFBeg3DsEDqhO/yBno10syN7+0RabfmazffDGdh/F8GR4nLWXyPuP9aX0qceEszB5l5BkOc2VGVUklCF+mc53JqY+D59pxC3ns+EvOR+2mMunoJekVqqJswbRozuEMimf8SbdKCq02e9oyPnvqnBVAvFw292/Je842S2qWXsJgbAKdWBFfjijv10wqAduaKktMCc/sq0mp1LofPrMKAk5+tGxx7MYYb/WbyHd4CL5sbjysnXE5YxFN5+SOFYbFTUs7CKfPvIeVP1rMuS2LzZFguVKo7GdYdnPBRmfjNkTs=
    username: AgAWHZwM4Z0XC2QpC9yl48gRjxSMtfIV2sCWiF3CuNaSJbsqGTQMqCaHhkgeSfExw1d9zt0Mm6d6zAxLLoXNczbgRn/PYQECr3btOuztGnvA0lqCba60lGa2i7C7317nyHWGAYvBrihmi8JKIgBGj1zJ71REusMTuUU4zSPhed3tvajjiciUaEAqJcRDVKEj6nxFXq/ZjrpeduRqbZjpglkB0yDh6LVyXhmX8XIQ4QHd9mw3i2lgZBrbrNOYxV+WQRvihBGyVNIQA4Mv9Ho4Hom6fgNsTU2lUc5W2ceVm0hNagbwKfAh6Gyz/AYANTPV97+iAFPeOby2Qiiu317JKhe13aqFAD3dIJ1Q5iLQdeFx890KJkF1YcMYFW4fvGJ+MeksJ3rqc/v9ZHb2tyytY8AIMImTTkwAczHlEwH5kn42cw9wDhjI3ZmGcA7LbmuHR+i0CvFZqhv9YmOUe76CWP53M0mKgO4NkgtPvfgfAm4vo0MO/dOg47eA8cwRzO6vEnCbs35dQXyMbSYH7h6Eb6EMqtwrbhl+ML5K5l72T/6qtKEsvuoxEGLp4UUO+dG3Ld4BfYwRX5mD7u6zfRrZnYePclx9/fKYGT+O8juysTt026KAWtMIotlCYwi9N5C1dWg050Z2SgJN0pq50DFLgKPsxRp93M5ASR6oCMdCvGVE+C5OaRd9fwd3mtfQ2+WRViRvz5kuRqk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: adminsecret
      namespace: planka
    type: Opaque