apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: planka-route
  namespace: planka
spec:
  hostnames:
    - "planka.virtualthoughts.co.uk"
  parentRefs:
    - name: cilium-api-gateway
      namespace: cilium
      sectionName: https-gateway
  rules:
    - backendRefs:
        - name: "planka"
          port: 1337
