apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secretkey
  namespace: planka
spec:
  encryptedData:
    key: AgB8wZEsVvNatLS9zE67pC05mTEJPu13PuKlh/JTXZZ3943Vg+9Gx+ECTdatxSYRoCl24NQqErl3BKOyQzHIIWnYjexdSB7w8P5k54u2T+fCP+s0+JMp0uGOxdJKn08AojMmrVbZTk+zhRSYSqc1eKdTf/qLwuK4/6dv5+93FcwTe/2Z6IFsFH+DPxyClv/ogW3ExvmuUF9yeC1fU/IxidBIqq9UwcRBVXtBCreUZmCTzz57rHifhZBh3CdlYCTSI/n2XNLlBAAwXu/7SGPiDe4vt6vFzqL2PnVXE48pa3mPnpcNDpyYpnvXhGqjqmPAWwQgsf1z63jrjFwc9NF1H/NkWWfv13GKTgGuseWM1DejCUk30ytMs+RWXSKC8xzlYPeyiNjrL/JzTAbR1fljqkv+g6pa6f13R7TZAp7g9pAGyHWswNjKMPwVUBv0JkgwEspfbrgeE1DZr80G1Q+1bf5rGQXu92t4eSY6cRL6Erqxr+cJW5LAMKc2AEcUIEg/JuJOZEtS+3VT0dOHf8YmEx1a0hF15oRR275b4ekYujhgV7WCKTLeZ6BOLhuOWrEqEsODuY5zP2QRC+JTvOv/j1Tqmkc5T6QVeXw/rGdyeS4gOxHqxUdSLSQgmcaw+ayocygCjoKqVojJ21usXmitIpIK4iAoZmKvFC/2S5MswbxkI4PIkNMDY7SQYt48rVW58ClN9INqr4owVBaGiA7H5vL0eTxJKdpe5K98avGi7rEjMjWJ0QfFMpVsvipSa6H3J8xXm8StdAwS2A5YW4tc8OWT637t3/D46YZSWCChVwDAf362p/p0n6bOOu+OTfPGgl4L9fvH7XtGoP/7xQIhcfkSbL9iOWFC6vwiV2j+dvZxlq4=
  template:
    metadata:
      name: secretkey
      namespace: planka
    type: Opaque
