apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: alert-manager-route
  namespace: kube-prometheus-stack
spec:
  hostnames:
    - "alertmanager.virtualthoughts.co.uk"
  parentRefs:
    - name: cilium-api-gateway
      namespace: cilium
  rules:
    - backendRefs:
        - name: "kube-prometheus-stack-alertmanager"
          port: 8080