apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: kube-prometheus-stack
spec:
  hostnames:
    - "grafana.virtualthoughts.co.uk"
  parentRefs:
    - name: cilium-api-gateway
      namespace: cilium
      sectionName: https-gateway
  rules:
    - backendRefs:
        - name: "kube-prometheus-stack-grafana"
          port: 80