apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
  namespace: cilium
spec:
  parentRefs:
    - name: cilium-api-gateway
      namespace: cilium
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: "https"
            statusCode: 301