apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hubble-route
  namespace: cilium
spec:
  hostnames:
    - "hubble.virtualthoughts.co.uk"
  parentRefs:
    - name: cilium-api-gateway
      namespace: cilium
  rules:
    - backendRefs:
        - name: "hubble-ui"
          port: 80