#kube-prometheus-stack:
#  prometheus:
#    prometheusSpec:
#      storageSpec:
#        volumeClaimTemplate:
#          spec:
#            storageClassName: longhorn
#            accessModes: ["ReadWriteOnce"]
#            resources:
#              requests:
 #               storage: 10Gi
#  alertmanager:
#    alertmanagerSpec:
#      storage:
#        volumeClaimTemplate:
#          spec:
#            storageClassName: longhorn
#            accessModes: ["ReadWriteOnce"]
#            resources:
#              requests:
#                storage: 50Gi
#  grafana:
#    persistence:
#      enabled: true
#      type: sts
#      storageClassName: longhorn
#      accessModes:
#        - ReadWriteOnce
#      size: 20Gi
#      finalizers:
#        - kubernetes.io/pvc-protection