apiVersion: grafana.integreatly.org/v1beta1
kind: grafanadatasource
metadata:
  name: loki-datasource
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: Loki
    type: loki
    access: proxy
    isDefault: false
    url: http://loki-gateway.loki.svc.cluster.local:80
