tempo:
  compactor:
    persistence:
      enabled: true
      size: 50Gi
  ingester:
    persistence:
      enabled: true
      size: 50Gi
    wal:
      enabled: true
  minio:
    enabled: true
    mode: standalone
    rootUser: grafana-tempo
    rootPassword: supersecret
    buckets:
      # Default Tempo storage bucket.
      - name: tempo-traces
        policy: none
        purge: false
    persistence:
      size: 50Gi
    configPathmc: '/tmp/minio/mc/'