apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
  labels:
    app: tdarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tdarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tdarr
    spec:
      containers:
        - name: tdarr
          image: ghcr.io/haveagitgat/tdarr:2.69.01
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Europe/London
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: ServerIP
              value: 0.0.0.0
            - name: ServerPort
              value: "8266"
            - name: webUIPort
              value: "8265"
            - name: internalNode
              value: "false"
            - name: nodeID
              value: Controller1
          ports:
            - containerPort: 8266
              name: server
              protocol: TCP
            - containerPort: 8265
              name: webui
              protocol: TCP
          volumeMounts:
            - mountPath: /app/configs
              name: tdarr-config
            - mountPath: /media-library
              name: media-library
            - mountPath: /app/server
              name: tdarr-server
            - name: tcache
              mountPath: /tcache
      volumes:
        - name: media-library
          nfs:
            path: /volume1/nas
            server: 192.168.88.228
        - name: tcache
          nfs:
            path: /volume1/nas/tdarr-cache
            server: 192.168.88.228
        - name: tdarr-config
          persistentVolumeClaim:
            claimName: tdarr-config
        - name: tdarr-server
          persistentVolumeClaim:
            claimName: tdarr-server
---
apiVersion: v1
kind: Service
metadata:
  name: tdarr
  labels:
    app: tdarr
spec:
  selector:
    app: tdarr
  ports:
    - name: webui
      port: 8265
      targetPort: 8265
      protocol: TCP
    - name: server
      port: 8266
      targetPort: 8266
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tdarr
  labels:
    app: tdarr
spec:
  parentRefs:
    - name: cilium-api-gateway
      sectionName: https-gateway
      namespace: cilium
  hostnames:
    - tdarr.virtualthoughts.co.uk
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: tdarr
          port: 8265
