apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi