wekan:

  ## Comma-separated string of allowed virtual hosts for external access.
  ## This should match the ingress hosts
  ##
  endpoint: wekan.virtualthoughts.co.uk

  ## Main URL (including http:// or https://) where your Wekan
  ## instance is accessible
  ##
  root_url: http://wekan.virtualthoughts.co.uk

  ingress:
    enabled: false
  
  resources:
    requests:
      memory: 128Mi
      cpu: 300m
    limits:
      memory: 1Gi
      cpu: 500m

  sharedDataFolder:
    enabled: true
    path: /data
    accessMode: ReadWriteOnce
    storageClass: longhorn
    resources:
      requests:
        storage: 5Gi

  mongodb:
    enabled: true
    image:
      # At the time of writing the mongodb chart defaults to version 8, but WeKan
      # needs 7.
      tag: 7.0.23
    storage:
      requestedSize: 2Gi
