planka:
  admin_email: admin@local.domain
  admin_name: admin
  existingSecretkeySecret: secretkey
  existingAdminCredsSecret: adminsecret
  baseUrl: "https://planka.virtualthoughts.co.uk"
  postgresql:
    enabled: false
    auth:
      database: planka
      username: planka
      password: ""
      postgresPassword: ""
      replicationPassword: ""
      # existingSecret: planka-postgresql
    serviceBindings:
      enabled: true
  dburl: postgres://planka:w7lqpJyCjw@planka-postgresql:5432/planka