#- name: Deploy Talos to Turing Pi
#  hosts: localhost
#  roles:
#    - 01-tpi-flash
#    - 02-talos-generate-config

#- name: Apply Control Plane configurations
#  hosts: control_plane
#  gather_facts: false # Talos nodes don't have Python, so gathering facts will fail
#  roles:
#    - 03-talos-apply-control-plane

#- name: Apply Worker configurations
#  hosts: workers
#  gather_facts: false # Talos nodes don't have Python, so gathering facts will fail
#  roles:
#    - 04-talos-apply-worker

- name: Bootstrap Cluster
  hosts: control_plane
  gather_facts: false # Talos nodes don't have Python, so gathering facts will fail
  roles:
    - 05-talos-bootstrap

- name: Extract Kubeconfig
  hosts: control_plane
  gather_facts: false # Talos nodes don't have Python, so gathering facts will fail
  roles:
    - 06-talos-extract-kubeconfig
