- name: Prepare Infrastructure
  hosts: localhost
  gather_facts: false
  roles:
    - 01-tpi-flash
    - 02-talos-generate-config

- name: Deploy Talos Control Plane
  hosts: control_plane
  connection: local
  gather_facts: false
  roles:
    - 03-talos-apply-control-plane

- name: Deploy Talos Workers
  hosts: workers
  connection: local
  gather_facts: false
  roles:
    - 04-talos-apply-worker

- name: Bootstrap and Install Core Services
  hosts: localhost
  gather_facts: false
  environment:
    KUBECONFIG: "{{ playbook_dir }}/talos-configs/kubeconfig"
  roles:
    - 05-talos-bootstrap
    - 06-talos-extract-kubeconfig
    - 07-talos-check-cluster-ready
    - 08-install-gateway-api-crds
    - 09-cluster-install-cilium
    - 10-install-cert-manager
    - 11-install-argocd
    - 12-generate-argocd-applications
