apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedora-desktop-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeMode: Block
---
apiVersion: batch/v1
kind: Job
metadata:
  name: upload-fedora-desktop-job
spec:
  template:
    spec:
      containers:
      - name: writer
        image: fedora:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            echo "[1/2] Downloading and decompressing Fedora Server image..."
            curl -L https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.10-preinstalled-desktop-arm64-turing-rk1.img.xz | xz -d > /tmp/disk.raw
            echo "[2/2] Writing image to PVC block device..."
            dd if=/tmp/disk.raw of=/dev/vda bs=4M status=progress conv=fsync
            echo "✅ Done writing Fedora Server image to PVC!"
        volumeDevices:
        - name: disk
          devicePath: /dev/vda
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 0
      restartPolicy: Never
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: fedora-desktop-pvc
      - name: tmp
        emptyDir: {}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-desktop
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora-desktop
    spec:
      domain:
        cpu:
          cores: 4
        resources:
          requests:
            memory: 4Gi
        devices:
          disks:
            - name: disk0
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      volumes:
        - name: disk0
          persistentVolumeClaim:
            claimName: fedora-desktop-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: kube
              password: changeme
              chpasswd: { expire: false }
---
apiVersion: v1
kind: Service
metadata:
  name: fedora-desktop-access
spec:
  ports:
    - name: ssh
      port: 22      # External port
      protocol: TCP
      targetPort: 22   # Port inside the VM for SSH
    - name: app
      port: 9090       # External port
      protocol: TCP
      targetPort: 9090 # Port inside the VM
  selector:
    kubevirt.io/domain: fedora-desktop
  type: LoadBalancer


