apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedora-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeMode: Block
---
apiVersion: batch/v1
kind: Job
metadata:
  name: upload-fedora-server-job
spec:
  template:
    spec:
      containers:
      - name: writer
        image: fedora:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            echo "[1/2] Downloading and decompressing Fedora Server image..."
            curl -L https://download.fedoraproject.org/pub/fedora/linux/releases/42/Server/aarch64/images/Fedora-Server-Host-Generic-42-1.1.aarch64.raw.xz | xz -d > /tmp/disk.raw
            echo "[2/2] Writing image to PVC block device..."
            dd if=/tmp/disk.raw of=/dev/vda bs=4M status=progress conv=fsync
            echo "✅ Done writing Fedora Server image to PVC!"
        volumeDevices:
        - name: disk
          devicePath: /dev/vda
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 0
      restartPolicy: Never
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: fedora-server-pvc
      - name: tmp
        emptyDir: {}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-server
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora-server
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: disk0
              disk:
                bus: virtio
      volumes:
        - name: disk0
          persistentVolumeClaim:
            claimName: fedora-server-pvc