on:
  pull_request:
    branches:
      - main
    paths:
      - /argocd-apps/**


jobs:
  upgrade-test:
    name: k3d ephemeral cluster
    runs-on: ubuntu-22.04

# We need to compare what's changed, ie the bump in version from an apps 
# values.yaml file. 

    steps:
      - name: Checkout Pull Request Branch (to detect changes)
        uses: actions/checkout@v4      

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v47.0.4
        with:
          dir_names: true
          files: /argocd-apps/*

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done