apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  hostnames:
    - "argocd.virtualthoughts.co.uk"
  parentRefs:
    - name: "cilium-gateway-{{ route_name }}"
      namespace: "{{ route_gateway_reference_namespace }}"
  rules:
    - backendRefs:
        - name: "{{ route_backend_service_name }}"
          port: "{{ route_backend_service_port }}"